### ISSUE TITLE
Device freezes when calling createPaymentTransactionNew_async

### ISSUE THREAD

**Issue by Scotty0448** [LedgerHQ/app-bitcoin-legacy#139]
I'm compiling ledger-app-btc with COIN=bitcoin_testnet and installing it on a Nano S with firmware 1.6.0 and Bitcoin 1.3.17 installed. Then I follow the usage instructions in the README, but the call to createPaymentTransactionNew_async returns with a timeout error and the Nano S freezes and has to be restarted.

If I open the installed Bitcoin 1.3.17 app instead, the call to createPaymentTransactionNew_async returns correctly with a signed transaction.

It also works if I compile with COIN=bitcoin_testnet but change the Makefile so that DEFINES_LIB is set back to blank and APP_LOAD_FLAGS is set to "--appFlags 0xa50" like it does for Bitcoin. My understanding is that those changes make the testnet app standalone and not rely on the installed Bitcoin app.

**Comment by gregdhill** [comment]
https://github.com/LedgerHQ/ledgerjs/issues/515
