### ISSUE TITLE
ledger nano s cannot verify and approve send transcription on device.

### ISSUE THREAD

**Issue by 0aliesl** [LedgerHQ/app-bitcoin-legacy#177]
my device cannot verfiy and approve send transcription, i resfactory my device, reinstal ledger live and clear my ledger live cash but not solved. just wait in loading page . i try in both of the ledger live windows 10 and ledger live android . no live chat and noanwser with support . and i need tell you just one of my wallets cannot verfiy and approve send transcription on the device. other wallets verify and approved. i need my BTCs emergency . please help me.|
@gre  @meriadec @valpinkman  @EricLarch @pollastri-pierre @btchip @onyb

**Comment by TamtamHero** [comment]
https://support.ledger.com/hc/en-us/articles/360006554854-How-to-contact-us
