### ISSUE TITLE
Installation of v1.6.1 failed on both of my devices

### ISSUE THREAD

**Issue by seanjsong** [LedgerHQ/app-bitcoin-legacy#191]
Yesterday I updated the firmware of my Nano X to 1.3.0, but the reinstallation of Bitcoin app failed.

Ethereum and Ripple apps can be installed successfully, during installation I can see the "Processing" and the spinner icon on the device. However, when installing Bitcoin app, nothing shows on the device, and the installation completes quickly. Bitcoin app icon never appears on the device.

Ledger Live Manager shows Bitcoin app installed successfully but it's not true, when I switch to the Accounts screen and then back to Manager screen, Bitcoin app is shown as not installed again.

Then I reset my Nano S device (firmware 2.0.0) and tried to install Bitcoin app, the same thing happened again. Ethereum app was installed successfully but Bitcoin app failed.

Then I tried several times, with Ledger Live 2.26.1 on MacOS 10.12.6 and MacOS 11.3.1. I also tried with Ledger Live iOS App. The results are all the same: The installation of Bitcoin app all failed!

My Nano S's firmware was update to 2.0.0 a few days ago, the reinstallation of all apps after updating firmware succeeded. But this time after resetting, the installation of Bitcoin app failed. I can only assume it is a bug of this new version 1.6.1 of Bitcoin app.

Now I lost access to all of my Bitcoin assets on both of my devices. What a sad day!

Please have a look and fix it as soon as you can!  Many thanks!

**Comment by TamtamHero** [comment]
There's been a deployment issue yesterday (my bad)
It's been fixed in the afternoon, sorry for the inconvenience :/
