### ISSUE TITLE
404 readme.md

### ISSUE THREAD

**Issue by bitpaint** [LedgerHQ/app-bitcoin-legacy#201]
There is a 404 here in the readme:

`
To compile and load it on a device, have a look here: https://ledger.readthedocs.io/en/latest/userspace/getting_started.html`

![image](https://user-images.githubusercontent.com/67663265/126845438-0dff190a-73c9-49e6-a128-73ee59062715.png)

**Comment by FabriceDautriat** [comment]
Thank you for noticing us.

Please have a look at the new documentation : https://developers.ledger.com/docs/nano-app/load/

**Comment by gruve-p** [comment]
Fixed with https://github.com/LedgerHQ/app-bitcoin/commit/4d5d1f4def760e7e48867eb7ba8434afead5fa4e
 
Issue can be closed
