### ISSUE TITLE
Incorrect display of bech32 addresses on Ledger device

### ISSUE THREAD

**Issue by Raulo** [LedgerHQ/app-bitcoin-legacy#21]
1.1.18 version of the Bitcoin application (the same with 1.1.10 on Testnet). Used with Electrum 3.0.5 and btchip_python-0.1.23. 

If the transaction has only one bech32 output, the displayed address on the device is incorrect, it shows P2PKH (starting with "1") address. It is signed correctly (tested on testnet). If there are more outputs (regardless of type), the bech32 address is displayed correctly. 

Also, P2WSH bech32 addresses are displayed without final symbols. They are longer than P2WPKH by 20 characters, and these are not displayed but the address is appended with "BTC" or "TEST" (on testnet).

**Comment by SomberNight** [comment]
> Also, P2WSH bech32 addresses are displayed without final symbols. They are longer than P2WPKH by 20 characters, and these are not displayed but the address is appended with "BTC" or "TEST" (on testnet).

Also described at https://github.com/spesmilo/electrum/issues/3544

**Comment by Raulo** [comment]
Fix (except for the P2WSH final symbols bug) is in https://github.com/LedgerHQ/blue-app-btc/pull/27

**Comment by NOkycTHX** [comment]
Hey i had this same issue where when setting up ledger live on new PC it showed wrong BTC balance was off by like 50% but i just went and used electrum.org bitcoin wallet and used there wallet recovery feature electrum-recovery.org to recover the ledger address and it showed my full balance if your having the same issue it could be worth trying

**Comment by SomberNight** [comment]
^ beware of scams...
(Comment above mentioning *-recovery.org malicious domain)

**Comment by bigspider** [comment]
Deleted, thanks @SomberNight!
