### ISSUE TITLE
Fake version 2.0.0 in Ledger Live

### ISSUE THREAD

**Issue by RoanBrand** [LedgerHQ/app-bitcoin-legacy#211]
Hi I just updated to a version 2.0.0 from the store:
![image](https://user-images.githubusercontent.com/14920090/141450781-e3cc0c44-8e58-42cd-b728-c7478d00f893.png)
This version does not seem to exist. Thus I cannot verify what I am running at the moment.
Please advise.

**Comment by bigspider** [comment]
Hello @RoanBrand. The new app is compiled from https://github.com/LedgerHQ/app-bitcoin-new.
Most likely, later we will move everything back to this repository, but as an interim solution we have two repos.

I will add a link to the new repo, thanks for your comment!
