### ISSUE TITLE
Has Ledger ever used Libbitcoin?

### ISSUE THREAD

**Issue by hanniabu** [LedgerHQ/app-bitcoin-legacy#244]
Libbitcoin Explorer (bx seed), used by many crypto wallets to generate private key entropy, is flawed and hackers have been silently draining people's money across multiple blockchains. https://milksad.info/

Has Ledger ever used Libbitcoin?

**Comment by bigspider** [comment]
No, `bx` is a linux command line tool, and no Ledger devices ever ran linux!
