### ISSUE TITLE
Cant connect via browser?

### ISSUE THREAD

**Issue by mandelmonkey** [LedgerHQ/app-bitcoin-legacy#32]
Hi
I am using the latest btc app ver 1.2.3 and nano s firmware 1.4.1 chrome Version 64.0.3282.186 (Official Build) (64-bit) on Mac OS

I am trying to get the address on the browser using the following code but I get the error

```Ledger device unreachable. Make sure the device is…unlocked and with the correct application opened.```

previously browser mode had to be set however in the new app the option is not available (I heard it was not needed anymore)

Cable seems to be ok, I can use the chrome btc app no problem

```
    if (TransportU2F.isSupported()) {

      TransportU2F.create().then(function(transport) {

        const btc = new Btc(transport);

        btc.getWalletPublicKey("44'/0'/0'/0").then(function(address) {

          console.log(address);

        }).catch(function(error) {

          console.log(error);

        });
      }).catch(function(error) {

        console.log(error);

      });
    }
```

**Comment by btchip** [comment]
The latest version is 1.2.4 - which adds back the U2F interface. It should work well with this version

**Comment by mandelmonkey** [comment]
I have updated to the btc app 1.2.4 but same issue, I also updated @ledgerhq/hw-transport-u2f to 4.7.0

id there something incorrect in my code?  here as a preview of the app trying https://ledgercptest.herokuapp.com/

```
if (TransportU2F.isSupported()) {

      TransportU2F.create().then(function(transport) {

        const btc = new Btc(transport);

        btc.getWalletPublicKey("44'/0'/0'/0").then(function(address) {

          console.log(address);

        }).catch(function(error) {

          console.log(error);

        });
      }).catch(function(error) {

        console.log(error);

      });
    }
```

**Comment by mandelmonkey** [comment]
can confirm issue addressed in ledgerjs update
https://github.com/LedgerHQ/ledgerjs/issues/112
