### ISSUE TITLE
Bug in KMD Ledger App

### ISSUE THREAD

**Issue by lukechilds** [LedgerHQ/app-bitcoin-legacy#60]
I’ve been contracted by a Komodo community member to build a third-party application to support Komodo interest claiming via a Ledger device. However, development is currently blocked because I’ve found a bug in the Komodo (KMD) Ledger app.

The KMD Ledger app is based on the BTC app codebase https://github.com/LedgerHQ/ledger-app-btc and so uses the same consensus rules to validate transactions. However, these consensus rules are slightly different in Komodo. Komodo has claimable interest which is calculated by the coinage of a given UTXO. Without going into too much detail, if the coinage is over a certain age and the value is over a certain amount, the UTXO is eligible to claim interest which means its next transaction can have a higher output value than input value. This causes two bugs in the current KMD Ledger app:

1. Valid KMD transactions are treated as invalid (because of BTC rules) and the Ledger will throw an error when you try and sign and it won’t be signed.

2. TX Fees are often shown with lower fees than what they really are because they don’t take the newly “minted” interest coins into account, these are given directly to the miners as fees.

We need to update the KMD firmware to respect the interest UTXO rules. It should allow output value of a greater amount than input value (under certain conditions including coinage and value of UTXO) and it should also take into account the interest amount when calculating TX fees.

It looks like maybe `transaction_amount_sub_be()` is the main culprit, although there may be some other modifications needed to correctly calculate the TX fee.

It seems like these issues could be relatively easily resolved by adding some small `if (G_coin_config->kind == COIN_KIND_KMD) {}` if statements to the BTC code so everything can continue to share the same codebase rather than forking off and maintaining a separate app just for KMD for a relatively small change.

Is this something you’d be willing to accept as a PR?

**Comment by super83** [comment]
This is just sad on Ledger customer service, because this been over a 1 year problems but no action from them, so i hope the Ledger Team can be more  professional and help fix this problems soon...because even Komodo Devs & Komodo community are willing to help them to fixed this wallet problems.

I personally bought a lots of their devices Ledger Nano S & Blue, so i really hope they start treating their customers right.....so sad :(

**Comment by lukechilds** [comment]
@super83 I'm working on this currently, I spoke with @btchip and he said they will review our changes and hopefully pull them into their official app. If not, we'll have a new third party Ledger app for claiming interest.

**Comment by lukechilds** [comment]
Chatlog from Ledger Devs Slack with @btchip for transparency:

```
lukechilds [11:49 AM]
Hey guys, I found a bug in the KMD Ledger app, it’s blocking my progress on a project so would really like to get it resolved ASAP. I’ve created a GitHub issue, more info over there: https://github.com/LedgerHQ/ledger-app-btc/issues/60
Thanks :slightly_smiling_face:

lukechilds [12:24 PM]
Happy to work with you on a solution for this but would like to know if you’re interested in merging such a change and how soon we can get it achieved

btchip [1:17 PM]
I'd rather have a different app considering that this change breaks btc logic
their decision to do that :panda_face:
also we won't support it in Live
so Ledger support would have to be integrated with their own wallet

lukechilds [3:02 PM]
@btchip This would make no difference in Live
it would just mean now the fee estimations would show up correctly instead of incorrect
I wouldn’t expect you to add interest claiming functionality in Live, that’s why they’ve contracted me to build a seperate app for them to do that
This fix in the KMD Ledger app would actually fix a current bug in Live (and all other apps that support Ledger on KMD)
and it wouldn’t “break” any BTC logic, only branch off to some slightly different TX fee calculation logic wrapped in a check for `if (G_coin_config->kind == COIN_KIND_KMD) {}`, I’ve seen this done for multiple other coins
So it would be some extra code added to the BTC code base that only affects KMD

lukechilds [3:12 PM]
however if you don’t want that (tiny) bloat in the KMD app then I respect your decision. They will still really want to keep their support in Live though, and it seems a bit complicated having two separate apps for the same currency (although not impossible if that’s what it comes to).

So what if we forked the current BTC app and modified the KMD bits as mentioned above? Could we get that approved as the official KMD app (replacing the existing one)? So users just need to update to the latest KMD app and only have to worry about having one app installed?

We would intentionally fork the official BTC app and keep it as similar as possible, only adding our changes wrapped in `if (G_coin_config->kind == COIN_KIND_KMD) {}` checks as described above. That way it makes it much simpler for you to review as you’ll be familiar with most of the code, and much easier for us to track your BTC codebase as an upstream branch and pull in new features if they’re added.

Would you be happy with that solution?

btchip [2:12 PM]
yes that's fine

lukechilds [2 days ago]
It's fine to submit a PR to the official app or fork off to our own?

btchip [2 days ago]
you can submit a PR. Worst case scenario we'll fork it ourselves

lukechilds [2 days ago]
Awesome, thanks so much!

Will get on this right away :tada:
```

**Comment by lukechilds** [comment]
Resolved via https://github.com/LedgerHQ/ledger-app-btc/pull/84
