### ISSUE TITLE
Base58 is broken in master

### ISSUE THREAD

**Issue by lukechilds** [LedgerHQ/app-bitcoin-legacy#81]
Building the master branch appears to have a broken Base58 implementation.

This commit appears to be the culprit: https://github.com/LedgerHQ/ledger-app-btc/commit/88668728e51d46655fcf09ae626322d0e35904d5 (PR https://github.com/LedgerHQ/ledger-app-btc/pull/76)

KMD has a P2PKH prefix of 0x3C which should result in a Base58 address prefix of 'R'.

If I checkout the commit mentioned and build the BTC+KMD apps I get multiple KMD addresses that don't start with 'R' and don't have valid Base58Check checksums. For example the derivation path `44'/141'/0'/0/5` should result in the KMD address `RNAeh18GPwx1udYAq5mZ3eJaU4d6f3ceom` but instead results in `6ecJtMem7cRudYAq5mZ3eJaU4d6f3ceom`.

If I checkout the previous commit before that and rebuild the apps everything works as expected.

**Commit 8866872: 6ecJtMem7cRudYAq5mZ3eJaU4d6f3ceom**

```js
await ledger.getWalletPublicKey(`44'/141'/0'/0/5`)
// {publicKey: "04dcc34020b171b54dea212462b32f711ec8cbb0ec3bafc5167e46511fca3a40079cfa8e0c444b81bd9200f03b5cb5330abe37a2a9575c4696bf21a8e1b9a85f5c", bitcoinAddress: "6ecJtMem7cRudYAq5mZ3eJaU4d6f3ceom", chainCode: "e0798cc24a5059fa63ebb89f24872481f92e8eacaa76c2fa179edf65de81976c"}
```

**Commit 992a2f4: RNAeh18GPwx1udYAq5mZ3eJaU4d6f3ceom**

```js
await ledger.getWalletPublicKey(`44'/141'/0'/0/5`)
// {publicKey: "04dcc34020b171b54dea212462b32f711ec8cbb0ec3bafc5167e46511fca3a40079cfa8e0c444b81bd9200f03b5cb5330abe37a2a9575c4696bf21a8e1b9a85f5c", bitcoinAddress: "RNAeh18GPwx1udYAq5mZ3eJaU4d6f3ceom", chainCode: "e0798cc24a5059fa63ebb89f24872481f92e8eacaa76c2fa179edf65de81976c"}
```

With the problematic build I checked the first 100 public KMD addresses and 23 were invalid.

I also checked up to the first 1000 BTC addresses and they were all ok.

**Comment by btchip** [comment]
Fixed by #88
