### ISSUE TITLE
0 fee transactions are accepted by the server but do not propagate

### ISSUE THREAD

**Issue by menkaur** [LedgerHQ/app-bitcoin-legacy#9]
Recently I tried sending 0-fee transactions from Bitcoin wallet and Bitcoin Cash wallet. In both wallets, the transaction was market as successful, and it shows in the app, but the transaction actually never confirms and if you check it out through the blockchain explorers, it's not found.

Here's an example BTC transaction:
3901cfd1ae18ab18ad442d36593158e3ecaa8396df87bf099a42e197ce36dc35

Resetting the app does not fix this issue

**Comment by btchip** [comment]
It's a complex issue which is related to our backend (so, not the device app). We don't have an ETA for an analysis and fix yet. Closing as we're already aware of it.

**Comment by menkaur** [comment]
There is a related issue in the chrome app.

When a wallet has transaction which needs confirming, and I try to send another transaction ( I have several confirmed addresses), I'm getting "Preparing transaction" window which never completes
